version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user_service_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    networks:
      - test-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  test-net:
